;;; phony.el --- Speech bindings for Elisp           -*- lexical-binding: t; -*-

;; Copyright (C) 2024, 2025 Erik Präntare

;; Author: Erik Präntare
;; Keywords: files
;; Version: 0.2.1
;; Homepage: https://github.com/ErikPrantare/phony.el
;; Package-Requires: ((emacs "29.1"))
;; Created: 13 Jul 2024

;; This program is free software; you can redistribute it and/or
;; modify it under the terms of the GNU Affero General Public License
;; as published by the Free Software Foundation, either version 3 of
;; the License, or (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU Affero General Public
;; License along with this program.  If not, see
;; <http://www.gnu.org/licenses/>.

;;; Commentary:

;;

;;; Code:

(require 'cl-lib)
(require 'subr-x)
(require 'map)

(require 'phony-element-syntax)

(defgroup phony nil
  "Functionality for defining speech bindings."
  :group 'files)

(defcustom phony-output-directory (locate-user-emacs-file "phony")
  "Directory for files generated by phony."
  :type 'directory
  :group 'phony)

(defcustom phony-form-evaluation-function #'phony-evaluate-form
  "Function used to evaluate lisp forms generated by phony.
Anytime a command is executed, this function is invoked with a form
containing the lisp code that should be executed to execute the
command."
  :type 'function
  :group 'phony)

(defun phony-evaluate-form (form)
  "Evaluate FORM.

If EmacsListen is installed and loaded, FORM is evaluated with
`emacslisten-evaluate'.  Otherwise, it is immediately evaluated with
`eval'."
  (if (fboundp #'emacslisten-evaluate)
      (emacslisten-evaluate form)
    (eval form)))

(defun phony--evaluate-form (form)
  "Evaluate FORM using `phony-form-evaluation-function'.

This is the actual function that gets invoked when a command is
recognized.  This function exists as a proxy to the evaluation function
so that it may be changed without reloading the grammar."
  (funcall phony-form-evaluation-function form))

(defun phony--output-directory (&rest components)
  "Get path to output directory.

If provided, COMPONENTS are appended as components in the returned path."
  (apply
   #'file-name-concat
   (expand-file-name phony-output-directory)
   components))

(defun phony--to-python-identifier (symbol)
  "Generate a fitting python identifier for SYMBOL.

This function is used to automatically generate external names for
rules."
  (concat "phony_" (replace-regexp-in-string (rx (not alnum)) "_" (symbol-name symbol))))

(cl-defstruct (phony--module
               (:constructor phony--make-module))
  "Modules group rules defined in a file into a unit.
See `phony-module' for information on how to define modules."
  ( name nil
    :type symbol
    :documentation
    "Name of this module.")
  ( utterance nil
    :type string
    :documentation
    "Utterance for referring to this module.")
  ( file-name nil
    :type string
    :documentation
    "Filename of the file defining this module.")
  ( enabled-p nil
    :type boolean
    :documentation
    "Whether the rules of this module should be exported."))

(defvar phony--modules-by-file-name (make-hash-table :test #'equal)
  "All modules, indexed by filename.")

(defun phony--current-file-name ()
  "Return the filename of the current evaluation context.

Returns `load-file-name' if non-nil, otherwise `buffer-file-name'.
Therefore, if both are nil, this function also returns nil.

The same file always returns the same path, unless the file has more
than one hardlink."
  (and-let* ((file-name (or load-file-name buffer-file-name)))
    (file-truename file-name)))

(define-multisession-variable phony--enabled-modules '()
  "Names of modules that are enabled across sessions.")

(defun phony--declare-module-of-current-file (name utterance)
  "Declare module named NAME for the current file.

UTTERANCE is a string specifying how this module is referred to as an
utterance."
  (let ((file-name (phony--current-file-name)))
    (cl-assert file-name nil "No current file could be found")
    (puthash file-name
             (phony--make-module
              :name name
              :utterance utterance
              :file-name file-name
              :enabled-p (memq name (multisession-value phony--enabled-modules)))
             phony--modules-by-file-name)
    (phony-dictionary-put utterance rule/phony-module name))
  name)

(defmacro phony-module (name &optional utterance)
  "Declare current file a phony module.

This will define a new module named NAME.  Rules declared in the file
that this form is evaluated in will be assigned to that module.

A module can be disabled or enabled.  If it is disabled, the rules
belonging to the module are not exported.  By default, newly defined
modules are disabled.  To enable a module, use `phony-enable-module'.

If given, UTTERANCE is a string specifying how this module is referred
to as an utterance."
  `(phony--declare-module-of-current-file ',name ',utterance))

(defun phony--current-module ()
  "Return the current module.

If the currently loaded or visited file does not define a module with
`phony-module', this function returns nil."
  (gethash (phony--current-file-name) phony--modules-by-file-name))

(defun phony--modules ()
  "Return list of all modules."
  (map-values phony--modules-by-file-name))

(defun phony--get-module (name)
  "Return module with NAME.

If no such module exists, this function returns nil."
  (seq-find (lambda (module) (eq (phony--module-name module) name))
            (phony--modules)))

(defun phony-enable-module (name &optional persist)
  "Enable module NAME.

If PERSIST is non-nil, the module will stay enabled across sessions.

Unless a module is enabled, the rules belonging to it are not
exported.  Rules not belonging to a module are always exported."
  (interactive (let* ((name (intern (completing-read
                                     "Enable phony module: "
                                     (seq-map #'phony--module-name
                                              (seq-remove #'phony--module-enabled-p
                                                          (phony--modules))))))
                      (persist (y-or-n-p (format "Enable %s for future sessions? " name))))
                 (list name persist)))
  (cl-assert (phony--get-module name) nil
             "No module named %s" name)
  (setf (phony--module-enabled-p (phony--get-module name)) t)
  (when persist
    (cl-pushnew name (multisession-value phony--enabled-modules)))
  (phony-request-export)
  (message "Enabled %s module" name))

(defun phony-disable-module (name &optional persist)
  "Disable module NAME.

If PERSIST is non-nil, the module will stay disabled across sessions.

Rules belonging to disabled modules are never exported."
  (interactive (let* ((name (intern (completing-read
                                     "Disable phony module: "
                                     (seq-map #'phony--module-name
                                              (seq-filter #'phony--module-enabled-p
                                                          (phony--modules))))))
                      (persist (y-or-n-p (format "Disable %s for future sessions? " name))))
                 (list name persist)))
  (cl-assert (phony--get-module name) nil
             "No module named %s" name)
  (setf (phony--module-enabled-p (phony--get-module name)) nil)
  (when persist
    (setf (multisession-value phony--enabled-modules)
          (delq name (multisession-value phony--enabled-modules))))
  (phony-request-export)
  (message "Disabled %s module" name))

(cl-defstruct (phony--rule
               (:constructor nil))
  "A rule for matching an utterance.

NAME is the name of the rule.

MODULE is a the module this rule belongs to.  Modules are specified with
`phony-module'.

MODES is a list of modes under which this rule is active.  If none of
the modes are active, this rule cannot be matched.  A special case is
the 'global symbol, which indicates that the rule should always be
active.

EXTERNAL-NAME is the name this rule will have for the speech recognition
engine, and should be a string.

WHEN is a predicate of no arguments which returns nil if the rule should
be inactive.  If WHEN is nil, it behaves as if it always returned t.

CONTRIBUTES-TO is a list of open rules that this rule contributes to."
  (name nil :type symbol)
  (module nil :type phony--module)
  (modes '(global) :type list)
  (external-name nil :type string)
  (when nil :type (function () t))
  (contributes-to '() :type list))

(defun phony--rule-active-p (rule)
  "Return non-nil if RULE is active.

A rule is inactive if it belongs to a disabled module or none of its
modes are currently active."
  (and
   (let ((modes (phony--rule-modes rule)))
     (or
      (memq 'global modes)
      (derived-mode-p modes)
      (seq-some (lambda (mode)
                  (or
                   (memq mode local-minor-modes)
                   (memq mode global-minor-modes)))
                modes)))
   (if-let ((module (phony--rule-module rule)))
       (phony--module-enabled-p module)
     t)
   (if-let ((when (phony--rule-when rule)))
       (funcall when)
     t)))

(cl-defstruct (phony--procedure-rule
               (:include phony--rule))
  (function '() :type function)
  (element nil :type phony--element-sequence)
  (arglist '() :type (repeat symbol))
  (export t :type boolean)
  (anchor-beginning-p nil :type boolean)
  (anchor-end-p nil :type boolean))

(cl-defstruct (phony--open-rule
               (:include phony--rule))
  (alternatives nil :type (repeat symbol))
  ;; TODO: Set explicitly to #'identity
  (transformation nil :type function))

(cl-defstruct (phony--dictionary
               (:include phony--rule)
               (:constructor nil)
               (:constructor phony--make-dictionary))
  "A dictionary mapping utterances to values.

NAME must be the symbol containing the mapping, an alist.

FORMAT-RAW-P is t if this dictionary is intended to be used on the
speech recognition side.  In that case, the mapping may only map to
strings."
  (format-raw-p nil :type boolean))

(defun phony--dictionary-alist (dictionary)
  "Return the alist stored in DICTIONARY."
  (funcall (phony--dictionary-name dictionary)))

(defun phony--normalize-rule (rule-or-name)
  "Return rule specified by RULE-OR-NAME.
RULE-OR-NAME must be a `phony--rule' or a symbol naming a rule."
  (if (symbolp rule-or-name)
      (phony--get-rule rule-or-name)
    rule-or-name))

(defun phony--external-name (rule-or-name)
  "Return the external name for RULE-OR-NAME.

The external name of a rule is a string, representing how the function
is identified when exported to the speech engine."
  (phony--rule-external-name
   (phony--normalize-rule rule-or-name)))

(defvar phony--rules (make-hash-table)
  "Hash table of all defined rules, indxed by name.")

(defun phony--get-rules ()
  "Return a list containing all defined rules."
  (hash-table-values phony--rules))

(defun phony--get-rule (name)
  "Get the rule named NAME.
Return nil if no such rule exists."
  (gethash name phony--rules))

(defun phony--add-rule (rule)
  "Add a new rule RULE.

RULE is added to the collection of rules.  If RULE was declared in a
file with a `phony-module' declaration, then RULE is put into that
module.

This function must be invoked every time a rule is declared."
  (setf (phony--rule-module rule) (phony--current-module))
  (puthash (phony--rule-name rule)
           rule
           phony--rules))

(defun phony-remove-rule (rule-name)
  "Remove rule named RULE-NAME."
  (interactive (list (intern (completing-read "Remove rule: "
                                              (hash-table-keys
                                               phony--rules)))))
  (remhash rule-name phony--rules)
  (seq-doseq (open-rule (seq-filter
                         #'phony--open-rule-p
                         (phony--get-rules)))
    (setf (phony--open-rule-alternatives open-rule)
          (remove rule-name (phony--open-rule-alternatives open-rule))))
  (phony-request-export))

(defun phony-dictionary-get (utterance dictionary)
  "Return the value corresponding to UTTERANCE in DICTIONARY.
If no such value exists, return nil."
  (funcall dictionary utterance))

(defmacro phony-dictionary-put (utterance dictionary value)
  "Set the value of UTTERANCE in DICTIONARY to VALUE.
If value is nil, remove the utterance from the list instead.

Invoking this function will resync the dictionary to the external speech
recognition engine."
  (declare (indent defun))
  `(,dictionary ,utterance ,value))

(gv-define-expander phony-dictionary-get
  ;; We need to use `gv-define-expander', because the simpler versions
  ;; expand to a let-expression binding the dictionary to a local
  ;; variable.  That meant removing  became impossible.
  (lambda (do utterance dictionary)
    (funcall do `(phony-dictionary-get ,utterance ,dictionary)
             (lambda (value)
               `(phony-dictionary-put ,utterance ,dictionary ,value)))))

(defun phony--create-lookup-representation (entry dictionary)
  "Create lookup string for ENTRY in DICTIONARY.

When evaluating the returned string from emacsclient, this performs
the lookup."
  (if (phony--dictionary-format-raw-p dictionary)
      (cdr entry)
    (format "(%s \"%s\")"
            (phony--dictionary-name dictionary)
            (car entry))))

(defun phony--prepare-dictionary-for-serialization (dictionary)
  "Return DICTIONARY as an entry for `json-serialize'.

This represents one key-value pair, mapping the external dictionary name
to its dictionary."
  (cons (make-symbol (phony--external-name dictionary))
        (mapcar (lambda (entry)
                  (cons
                   (make-symbol (car entry))
                   ;; Each value is a string, encoding a form that
                   ;; will evaluate to the actual value.
                   (phony--create-lookup-representation
                    entry dictionary)))
                (phony--dictionary-alist dictionary))))

;; TODO: Handle IO errors
(defun phony--export-dictionaries ()
  "Write dictionaries to dictionaries.json.

The speech recognition backend can read this file to register the
dictionaries."
  (mkdir (phony--output-directory) t)
  (with-temp-file (phony--output-directory "dictionaries.json")
    (json-insert
     (mapcar #'phony--prepare-dictionary-for-serialization
             (seq-filter #'phony--dictionary-p (phony--get-rules))))))

(defvar phony--deny-export-requests-p nil
  "Non-nil if requests to export should always be denied.")

(defun phony--request-export-dictionaries ()
  "Sync DICTIONARY-NAMES when next idle."
  (interactive)
  (unless phony--deny-export-requests-p
    (cancel-function-timers #'phony--export-dictionaries)
    (run-with-idle-timer 0.0 nil #'phony--export-dictionaries)))

(cl-defun phony--define-dictionary (name
                                    mapping
                                    &key
                                    external-name
                                    (mode 'global)
                                    format-raw
                                    contributes-to)
  "Define dictionary rule NAME containing MAPPING.

If FORMAT-RAW is t, the dictionary will be formated for use on the side
of the speech recognition engine.  This only works if the values of the
dictionary are strings.

MODE, CONTRIBUTES-TO and EXTERNAL-NAME are the same as for `phony-rule'."
  (unless external-name (setq external-name (phony--to-python-identifier name)))
  (setq mode (ensure-list mode))

  (unless (proper-list-p mapping)
    (error "The mapping of %s must be a list" name))

  (when-let ((non-cons (seq-find (lambda (x) (not (consp x))) mapping)))
    (error "The mapping of %s must be a alist, but %S is not a cons cell"
           name non-cons))

  (when-let ((non-string-key (seq-find
                              (lambda (entry) (not (stringp (car-safe entry))))
                              mapping)))
    (error "The keys of %s must be strings, but %S is not a string"
           name (car non-string-key)))

  (setq name (phony--normalize-rule-name name))

  (defalias name
    (lambda (&optional utterance-or-alist new-value)
      (:documentation (concat "Return the alist of dictionary `"
                              (symbol-name name)
                              "'.\nIf UTTERANCE, a string, is given, return instead the corresponding
value of the alist.  If NEW-VALUE is provided but not UTTERANCE,
reassign instead the full dictionary to NEW-VALUE.  If NEW-VALUE and
UTTERANCE are both provided, reassign instead UTTERANCE to NEW-VALUE.

Upon modification of the dictionary, it is also exported.

\(fn [UTTERANCE] NEW-VALUE)"))
      (if (stringp utterance-or-alist)
          (if new-value
              (progn
                (setf (alist-get utterance-or-alist mapping nil nil #'equal)
                      new-value)
                (phony--request-export-dictionaries))
            (alist-get utterance-or-alist mapping nil nil #'equal))
        (if utterance-or-alist
            (progn
              (setq mapping utterance-or-alist)
              (phony--request-export-dictionaries))
          mapping))))

  (eval `(gv-define-simple-setter ,name ,name))

  (phony--add-rule
   (phony--make-dictionary
    :name name
    :external-name external-name
    :format-raw-p format-raw
    :modes mode
    :contributes-to (seq-map #'phony--normalize-rule-name
                             (ensure-list contributes-to))))

  (if (or contributes-to (not (memq 'global mode)))
      (phony-request-export)
    (phony--request-export-dictionaries)))

(defun phony--split-keywords-rest (declaration-args)
  "Split DECLARATION-ARGS into keyword arguments and rest arguments.

Keyword arguments are assumed to occur first.  Returns a cons-cell with
the car being a plist of the keyword arguments and the cdr the rest
arguments."
  (let ((arguments '()))
    (while (keywordp (car declaration-args))
      (push (seq-take declaration-args 2) arguments)
      (setq declaration-args (seq-drop declaration-args 2)))
    (cons (apply #'append arguments) declaration-args)))

(defmacro phony-define-dictionary (name &rest arguments)
  ;; checkdoc-params: (arguments)
  "Define a dictionary with NAME containing ALIST.

ALIST is an alist mapping utterances to values.  An utterance is a
string containing the spoken form for referencing the value.  The
defined rule matches on any of the keys and evaluates to the
corresponding value.

Optional arguments are given as named arguments before ALIST.  They can
be one of the following:

  :format-raw       Export values in a form usable by the engine,
                    not Emacs.  This only works when the values are
                    strings.
  :mode             Same as for `phony-rule'.
  :external-name    Same as for `phony-rule'.
  :contributes-to   Same as for `phony-rule'.

\(fn NAME [KEY VALUE]... ALIST)"
  (declare (indent defun))
  (let* ((split-arguments (phony--split-keywords-rest arguments))
         (optional-arguments (car split-arguments))
         (alist (cadr split-arguments)))

    (when (map-elt optional-arguments :contributes-to)
      (setf (map-elt optional-arguments :contributes-to)
            `',(ensure-list (map-elt optional-arguments :contributes-to))))

    `(phony--define-dictionary
      ',name
      ,alist
      ,@optional-arguments)))

(defun phony--add-alternative (alternative open-rule-name)
  "Add rule ALTERNATIVE as an alternative for open rule OPEN-RULE-NAME."
  (let ((rule (phony--get-rule open-rule-name)))
    (unless rule
      (error "No rule %s defined" open-rule-name))
    (unless (phony--open-rule-p rule)
      (error "No open rule %s defined" open-rule-name))
    (cl-pushnew alternative (phony--open-rule-alternatives rule))))

(cl-defun phony--define-open-rule (name
                                   &key
                                   alternatives
                                   contributes-to
                                   transformation
                                   external-name
                                   mode)
  "See documentation for `phony-define-open-rule'."
  (unless external-name (setq external-name (phony--to-python-identifier name)))
  (setq mode (ensure-list (or mode 'global)))

  (cl-assert (symbolp transformation) nil
             "Transformation argument to rule %S must be a symbol"
             name)

  (setq name (phony--normalize-rule-name name))

  ;; For finding the definition of this rule
  (defalias name (lambda (&rest _) nil)
    "Open rule for phony.")

  (phony--add-rule
   (make-phony--open-rule
    :name name
    :external-name external-name
    :transformation transformation
    :alternatives (seq-map #'phony--normalize-rule-name alternatives)
    :modes mode
    :contributes-to (seq-map #'phony--normalize-rule-name
                             (ensure-list contributes-to))))

  name)

(cl-defmacro phony-define-open-rule (name
                                     &key
                                     alternatives
                                     contributes-to
                                     transformation
                                     mode
                                     external-name)
  "Define NAME as an open rule.

Open rules match any of the rules specified in ALTERNATIVES.  Other
rules may add themselves to the list of alternatives by specifying
this rule in their CONTRIBUTES-TO argument.

The value of matching this rule is the value of matching the
corresponding alternative.  If a function TRANSFORMATION is given, the
value is first passed through TRANSFORMATION.  Otherwise, the value is
passed through without modification.

Optional keyword arguments MODE, CONTRIBUTES-TO and EXTERNAL-NAME are
the same as for `phony-rule'."
  (declare (indent defun))
  `(phony--define-open-rule
    ',name
    :alternatives ,alternatives
    :contributes-to ',contributes-to
    :transformation ,transformation
    :external-name ,external-name
    :mode ,mode))

(defun phony--element-children (element)
  "Return all direct sub-elements of ELEMENT."
  (cl-typecase element
    (phony--element-sequence
     (phony--element-sequence-elements element))
    (phony--element-optional
     (list (phony--element-optional-element element)))
    (phony--element-zero-or-more
     (list (phony--element-zero-or-more-element element)))
    (phony--element-one-or-more
     (list (phony--element-one-or-more-element element)))
    (phony--element-argument
     (list (phony--element-argument-element element)))
    (t nil)))

(defun phony--collect (predicate element)
  "Return list of descendants of ELEMENT matching PREDICATE.

If ELEMENT matches PREDICATE, it will be part of the list.  Matches are
returned in the same order that they occur in ELEMENT."
  (let ((collected-children
         (seq-mapcat
          (apply-partially #'phony--collect predicate)
          (phony--element-children element))))
    (if (funcall predicate element)
        (cons element collected-children)
      collected-children)))

(defun phony--dependencies (rule-or-name)
  "Return list of names of the rules RULE-OR-NAME depends on."
  (phony--dependencies-implementation
   (phony--normalize-rule rule-or-name)))

(cl-defgeneric phony--dependencies-implementation (rule)
  "Return list of rule names RULE depends on.")

(cl-defmethod phony--dependencies-implementation ((rule phony--procedure-rule))
  "Return list of rule names RULE depends on.

Rules in the list occur the same amount of times they are referenced in
RULE."
  (seq-map #'phony--element-rule-name
           (phony--collect
            #'phony--element-rule-p
            (phony--procedure-rule-element rule))))

(cl-defmethod phony--dependencies-implementation ((rule phony--open-rule))
  "Return names of the alternatives of RULE."
  (phony--open-rule-alternatives rule))

(cl-defmethod phony--dependencies-implementation ((_rule phony--dictionary))
  "Return nil."
  '())

(cl-defgeneric phony--references (rule-or-name)
  "Return list of references of RULE-OR-NAME.

Each element of the list is a cons cell (NAME . CONTRAVARIANT).  NAME is
a symbol naming the referred to function.  CONTRAVARIANT is non-nil if
the reference has the effect of NAME potentially matching RULE-OR-NAME.
This happens with the :contributes-to parameter.  If CONTRAVARIANT is
nil, the reference has the effect of RULE-OR-NAME matching NAME."
  (let ((rule (phony--normalize-rule rule-or-name)))
    (append (seq-map (lambda (reference) (cons reference nil))
                     (phony--dependencies rule))
            (seq-map (lambda (reference) (cons reference t))
                     (phony--rule-contributes-to rule)))))

(cl-defstruct (phony--analysis-data
               (:constructor nil)
               (:constructor phony--make-analysis-data))
  "Storage struct for results of statically analyzing the grammar."
  (forward
   (make-hash-table)
   :type hash-table
   :documentation "Hash table mapping a rule to a list of its dependencies.
If a dependency is referred to multiple times, it is duplicated.")
  (backward
   (make-hash-table)
   :type hash-table
   :documentation "Hash table mapping a rule to a list of its dependents.
If a dependent refers to a rule multiple times, it is duplicated.")
  (cycle
   nil
   :type list
   :documentation "If non-nil, a sequence of rule names forming a dependency cycle.")
  (contains-errors
   nil
   :type boolean
   :documentation "Whether the analysis detected errors in the grammar.")
  (linear-extension
   nil
   :type list
   :documentation "Linear extension of the dependency graph.
Also commonly known as topological order.  Rules occurring in this list
are guaranteed to only depend on preceding rules."))

(defun phony--backward-references (analysis-data rule-or-name)
  ;; checkdoc-params: (analysis-data)
  "Get list of rules referring to RULE-OR-NAME.

If a rule refers to RULE-OR-NAME. multiple times, it will also occur as
many times in the returned list."
  (gethash (phony--normalize-rule rule-or-name)
           (phony--analysis-data-backward analysis-data)))

(defun phony--forward-references (analysis-data rule-or-name)
  ;; checkdoc-params: (analysis-data)
  "Get list of rules referred to by RULE-OR-NAME.

If a rule is referred to by RULE-OR-NAME. multiple times, it will also
occur as many times in the returned list."
  (gethash (phony--normalize-rule rule-or-name)
           (phony--analysis-data-forward analysis-data)))

(defun phony--maximum-backward-multiplicity (analysis-data rule)
  ;; checkdoc-params: (analysis-data)
  "Return maximum amount of times RULE is referred to by a single rule."
  (thread-last
    (phony--backward-references analysis-data rule)
    (seq-map #'phony--rule-name)
    (seq-map #'symbol-name)
    (seq-sort #'string<)
    (seq-group-by #'identity)
    (seq-map #'cdr)
    (seq-map #'length)
    (apply #'max 0)))

(defun phony--populate-dependency-graph (analysis-data)
  "Populate the dependency graph of ANALYSIS-DATA.

If an undefined rule is referenced in some element, a warning will be
emitted and `phony--analysis-data-contains-errors' will be set to nil."
  (let ((dependencies (make-hash-table))
        (dependents (make-hash-table)))
    (seq-doseq (rule (phony--get-rules))
      (puthash rule '() dependencies)
      (puthash rule '() dependents))
    (seq-doseq (rule (phony--get-rules))
      (seq-doseq (reference (phony--references rule))
        (if-let* ((reference-rule (phony--get-rule (car reference))))
            (if (cdr reference)
                (progn
                  (push rule (gethash reference-rule dependencies))
                  (push reference-rule (gethash rule dependents)))
              (push reference-rule (gethash rule dependencies))
              (push rule (gethash reference-rule dependents)))
          (display-warning 'phony
                           (format "Rule %S (referenced in %S) is not defined"
                                   (car reference)
                                   (phony--rule-name rule)))
          (oset analysis-data contains-errors t)))
      (oset analysis-data forward dependencies)
      (oset analysis-data backward dependents))))

(defun phony--try-linear-extension-impl (rule visited finished analysis-data)
  "Find linear extension of dependency graph in ANALYSIS-DATA.

This function assumes that `phony--analysis-data-forward' has been
populated in ANALYSIS-DATA.

This function populates `phony--analysis-data-linear-extension' in
ANALYSIS-DATA.  If a cycle is detected
`phony--analysis-data-contains-errors' is set to t and the cycle is
returned without visiting any more rules.  Otherwise, this function
returns nil.

RULE is the currently visited rule.  VISITED is a hash table of the
already visited rules.  FINISHED is a hash table of rules that have been
fully processed.  This function adds RULE to VISITED before recusing to
its children, and to FINISHED afterwards."
  (let ((dependencies (oref analysis-data forward)))
    (cl-block nil
      (when (gethash rule finished)
        (cl-return nil))
      (when (gethash rule visited)
        (cl-return (list rule)))

      (puthash rule t visited)
      (seq-doseq (dependency (gethash rule dependencies))
        (when-let ((path (phony--try-linear-extension-impl
                          dependency visited finished analysis-data)))
          (if (and (not (length= path 1))
                   (eq (seq-first path) (car (last path))))
              (cl-return path)
            (cl-return (cons rule path)))))

      (puthash rule t finished)
      (push rule (oref analysis-data linear-extension))
      (cl-return nil))))

(cl-defun phony--try-linear-extension (analysis-data)
  "Try to construct the linear extension of dependency graph.

This function assumes that `phony--analysis-data-forward' has been
populated in ANALYSIS-DATA.

If it is not possible to create a linear extension because of a cycle,
`phony--analysis-data-cycle' of ANALYSIS-DATA is set to that cycle and
`phony--analysis-data-contains-errors' is set to t.  Otherwise,
`phony--analysis-data-linear-extension' is populated with a valid linear
extension."
  (let ((visited (make-hash-table))
        (finished (make-hash-table)))
    (seq-doseq (rule (phony--get-rules))
      (when-let ((cycle (phony--try-linear-extension-impl
                         rule visited finished
                         analysis-data)))
        (oset analysis-data cycle (seq-map #'phony--rule-name cycle))
        (cl-return-from phony--try-linear-extension)))))

(defvar phony--last-analysis nil
  "Results of the last performed analysis.")

(defun phony--analyze-grammar ()
  "Analyze the grammar.

This returns a `phony--analysis-data' structure populated with the
results of the analysis."
  (let ((analysis-data (phony--make-analysis-data)))
    (phony--populate-dependency-graph analysis-data)
    (phony--try-linear-extension analysis-data)
    (setf (phony--analysis-data-linear-extension analysis-data)
          (reverse
           (phony--analysis-data-linear-extension analysis-data)))
    (when-let (cycle (phony--analysis-data-cycle analysis-data))
      (display-warning 'phony (concat "Cycle found: "
                                      (string-join
                                       (seq-map #'symbol-name cycle)
                                       " -> ")))
      (setf (phony--analysis-data-contains-errors analysis-data) t))
    (setq phony--last-analysis analysis-data)
    analysis-data))

(defun phony--dependents (rule-or-name)
  "Return dependents of RULE-OR-NAME.

This function depends on `phony--last-analysis'.  If an analysis has not
been performed, the returned value may be out of date."
  (gethash
   (phony--normalize-rule rule-or-name)
   (phony--analysis-data-backward phony--last-analysis)))

(defcustom phony-export-function #'phony-talon-export
  "Function to be used for exporting spoken rules."
  ;; Using radio instead of choice did not display :tag
  :type '(choice (function-item :tag "Dragonfly exporter"
                                phony-dragonfly-export)
                 (function-item :tag "Talon exporter"
                                phony-talon-export))
  :tag "Phony Rule Exporter"
  :risky t
  :group 'phony)

(defun phony--export-all ()
  "Export all rules to the speech recognition engine.

If any errors are detected in the grammar, the rules are not exported."
  (let ((analysis-data (phony--analyze-grammar)))
    (if (phony--analysis-data-contains-errors analysis-data)
        (display-warning 'phony "Grammar contains errors, not exporting")
      (phony--export-dictionaries)
      (when (and (not (server-running-p))
                 (y-or-n-p "Emacs needs to run as a daemon for phony to work.  Start daemon?"))
        (server-start))
      (cancel-function-timers #'phony--sync-state)
      (run-with-idle-timer 0.1 t #'phony--sync-state)
      (funcall phony-export-function analysis-data))))

(defun phony-request-export ()
  "Export all rules when next idle.

If `phony--deny-export-request-p' is non-nil, just return immediately
instead."
  (interactive)
  (unless phony--deny-export-requests-p
    (cancel-function-timers #'phony--export-all)
    (run-with-idle-timer 0 nil #'phony--export-all)))

(cl-defun phony--export-rule (function
                              arglist
                              element-forms
                              &key
                              (mode 'global)
                              contributes-to
                              external-name
                              (export t)
                              anchor-beginning
                              anchor-end
                              when)
  ;; checkdoc-params: (mode contributes-to external-name export anchor-beginning anchor-end)
  "Declare FUNCTION to be a rule invokeable by voice.

ARGLIST is the argument list of the function.  ELEMENT-FORMS is a list of
element forms specifying how to match this rule.

For the named arguments and the specification of element forms, see the
documentation for `phony-rule'."
  (setq arglist (byte-compile-arglist-vars arglist))
  (setq mode (ensure-list mode))
  (unless external-name (setq external-name (phony--to-python-identifier function)))
  (phony-remove-rule function)
  ;; TODO: Add element form checks:
  ;; - Each argument may only occur at most once.
  ;; - Arguments may only be bound to value creating elements.  (May
  ;;   already be done implicitly in parsing?)
  ;; - Rule may not be potentially empty (talon and dragonfly(?)
  ;;   limitation)
  (phony--add-rule
   (make-phony--procedure-rule
    :name function
    :external-name external-name
    :function function
    :element (phony--parse-speech-element
              (cons 'seq element-forms)
              (byte-compile-arglist-vars arglist))
    :arglist arglist
    :modes mode
    :when when
    :export export
    :contributes-to (seq-map #'phony--normalize-rule-name
                             (ensure-list contributes-to))
    :anchor-beginning-p anchor-beginning
    :anchor-end-p anchor-end))

  (phony-request-export))

(cl-defun phony--speech-declaration (function arglist &rest declaration-args)
  ;; checkdoc-params: (arglist declaration-args)
  "Declare FUNCTION to be a rule invokeable by voice.

This function should not be called directly, but through a `phony-rule'
form."
  (let* ((split-args (phony--split-keywords-rest declaration-args))
         (optional-arguments (car split-args))
         (pattern (cdr split-args)))

    (when (map-elt optional-arguments :contributes-to)
      (setf (map-elt optional-arguments :contributes-to)
            `',(ensure-list (map-elt optional-arguments :contributes-to))))

    `(phony--export-rule
      #',function
      ',arglist
      ',pattern
      ,@optional-arguments)))

(setf (alist-get 'phony-rule defun-declarations-alist)
      (list #'phony--speech-declaration))

(defmacro phony-rule (args)
  ;; checkdoc-params: (args)
  "Declare function to be a rule invokeable by voice.

This form must occur inside a `declare' form to take effect.

ELEMENTS is a sequence of elements declaring when this rule gets
matched.  An element may have one of the following forms:

  STRING           Match a literal STRING.
  SYMBOL           Match a rule named SYMBOL.
  (ARG SYMBOL)     Match a rule named SYMBOL, bind its value to argument
                   ARG.  ARG must be part of the function's arglist.
  (seq ELEMS...)   Match elements ELEMS.
  (? ELEMS...)     Optionally match elements ELEMS.
  (* ELEMS...)     Match elements ELEMS zero or more times.
  (+ ELEMS...)     Match elements ELEMS one or more times.

Optional arguments for the rule are given before ELEMENTS as a sequence
of alternating KEY and VALUE.  Optional arguments are:

  :export            If nil, this rule cannot be spoken directly but may
                     occur as part of other rules.  Default is t.
  :mode              A mode or list of modes for this rule should be
                     active.  If none of the modes match, this rule
                     never matches.  As a special case, 'global always
                     matches.  Default is 'global.
  :when              A function of no arguments returning non-nil when
                     this rule should be active.  If this argument
                     omitted provided, it behaves as if a function
                     always returning t was provided.
  :contributes-to    An unquoted symbol or list of symbols of open
                     rules that this procedure should contribute to.
                     See `phony-define-open-rule' for open rules.
                     Default is nil.
  :anchor-beginning  If t, this rule must occur first in an utterance.
                     Default is nil.
  :anchor-end        If t, this rule must occur last in an utterance.
                     Default is nil.
  :external-name     If given, this rule will be given this name for
                     the external speech engine.  Otherwise, it gets
                     assigned an unspecified auto-generated name.

\(fn [KEY VALUE]... ELEMENTS...)"
  `(message "Stray `phony-rule' form: %S" '(phony-rule . ,args)))

(defmacro phony-defun (name pattern &rest rest)
  (declare (indent 2)
           (doc-string 3))
  ;; Tooling that we want to work before we are ready to ship this:
  ;; - xref: DONE
  ;; - completion-at-point: DONE
  ;; - syntax highlighting for keywords

  ;; Other todos:
  ;; - Do not hijack the function namespace.  The tooling may need to
  ;;   be revisited after this.
  ;; - Check TODOs for better error messages.

  ;; Syntactical design decisions:
  ;; - Automatic argument deduction: Explicitly specifying the
  ;;   argument list meant that adding a parameter necessitated a
  ;;   change in two places.  Things like optional arguments were not
  ;;   semantically relevant in the argument list, as they would
  ;;   always be populated with nil anyway.
  ;; - Optional parameters after docstring: The doc-string declare
  ;;   form only allows a constant, so comment syntax highlighting
  ;;   would not be possible the other way around.
  ;; - Elision of parentheses when pattern is just a literal: Allows the
  ;;   following nice looking syntax:
  ;;   (phony-defun chuck-line "chuck line"
  ;;     (kill-line))
  ;; - Pattern after name, before doc-string:
  ;;   - I want the pattern to be indented specially, but not for
  ;;     documentation.  The indent declare form allows this if
  ;;     pattern is before documentation.
  ;;   - If it was the other way around and documentation was omitted,
  ;;     the elision of parentheses for string literals could trick
  ;;     the syntax highlighting to treat the test documentation.
  ;; - Implicit argument naming: This allows the following terse
  ;;   syntax for simple rules:
  ;;   (phony-defun chuck-thing ("chuck" thing)
  ;;     (kill-thing thing))
  ;;   This will be useful when rules don't share namespace with
  ;;   functions anymore, allowing shorter names.
  ;; - Name phony-defun: Chosen because of the similarity with defun.
  ;;   However, this could potentially give the impression that we are
  ;;   defining a function, something that may not be true in the future.
  ;; - Implicit seq for sequence of elements: In practice, this is the
  ;;   most common construction to use at the top level (perhaps
  ;;   excepts a single string literal, which is also covered by
  ;;   shorthand).  Might as well allow eliding it.
  ;; - Unquoted :contributes-to: By restricting the legal forms that
  ;;   may be passed to it, we can better utilize capf and xref.  For
  ;;   example, we know that function names cannot appear in the form,
  ;;   so those may be filtered out from completion and
  ;;   go-to-definition.
  (let* ((doc (and (stringp (car rest)) (pop rest)))
         (split-arguments (phony--split-keywords-rest rest))
         (optional-arguments (car split-arguments))
         (body (cdr split-arguments))
         (expanded-pattern
          (phony--expand-implicit-arguments
           (cons 'seq (ensure-list pattern))))
         (arguments (phony--collect-arguments expanded-pattern)))

    (cond
     ((not (seq-every-p (lambda (argument) (memq argument (flatten-tree body)))
                        (seq-remove (lambda (argument)
                                      (string-prefix-p "_" (symbol-name argument)))
                                    arguments)))
      ;; TODO: Which arguments?
      `(display-warning
        'phony
        ,(format "Not all arguments used in body of %s" name)))
     ((not (equal (seq-uniq arguments) arguments))
      ;; TODO: Do not emit this warning if duplication is implicit and
      ;; not used in body.
      `(display-warning
        'phony
        ,(format (concat "Duplicate arguments in %s\n"
                         "If you use implicit argument names, make them explicit")
                 name)))
     (t `(defun ,(phony--normalize-rule-name name) ,arguments
           ,@(ensure-list doc)
           (declare (phony-rule
                     ,@optional-arguments
                     ,expanded-pattern))
           ,@body)))))

(defun phony--normalize-rule-name (name)
  "Normalize NAME to include the rule/ prefix.
If NAME already starts with rule/, return it unchanged."
  ;; This is intended to be temporary
  (if (string-prefix-p "rule/" (symbol-name name))
      name
    (intern (concat "rule/" (symbol-name name)))))

(defun phony--expand-implicit-arguments (element-form)
  (cond
   ((and (listp element-form) (memq (car element-form) '(seq ? + *)))
    `(,(car element-form)
      ,@(seq-map #'phony--expand-implicit-arguments (cdr element-form))))
   ((symbolp element-form)
    `(,element-form ,element-form))
   (t element-form)))

(defun phony--collect-arguments (element-form)
  (cond
   ((and (listp element-form) (memq (car element-form) '(seq ? + *)))
    (seq-mapcat #'phony--collect-arguments (cdr element-form)))
   ((listp element-form)
    (list (car element-form)))
   (t '())))

(let ((phony--deny-export-requests-p t))
  ;; Define all builtin rules here.  We suppress export, as the user
  ;; may not have set the correct exporter yet.
  (phony-define-dictionary phony-module '())

  (phony-defun phony-enable-module ("phony enable" (? (name phony-module)))
    (if name
        (phony-enable-module name (y-or-n-p (format "Enable %s for future sessions? " name)))
      (call-interactively #'phony-enable-module)))

  (phony-defun phony-disable-module ("phony disable" (? (name phony-module)))
    (if name
        (phony-disable-module name (y-or-n-p (format "Disable %s for future sessions? " name)))
      (call-interactively #'phony-disable-module))))

(defun phony--sync-state ()
  ;; We must filter the enabled rules before doing with-temp-file, as
  ;; that may otherwise influence which rules are enabled.
  (let ((active-rules (seq-filter #'phony--rule-active-p (phony--get-rules))))
    (with-temp-file (phony--output-directory "active-rules")
      (insert (string-join
               (seq-map #'phony--rule-external-name active-rules)
               "\n")
              "\n"))))

(require 'phony-talon)
(require 'phony-dragonfly)

(provide 'phony)
;;; phony.el ends here
